### ISSUE TITLE
AWS::EKS::Cluster without 'Version' property will not create latest cluster version

### ISSUE THREAD

**Issue by pahud** [aws-samples/amazon-eks-refarch-cloudformation#9]
For example, the following cfn template will create `1.12` in `ap-northeast-1` 

```
AWSTemplateFormatVersion: 2010-09-09

Resources:
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: demo
      ResourcesVpcConfig:
        SecurityGroupIds: 
          - sg-0153bc41936cad87d
        SubnetIds: 
            - subnet-050196ad9cabc770d
            - subnet-01dc57b9cb22345b4
            - subnet-00a56b14600908367
      RoleArn: arn:aws:iam::903779448426:role/EKS-CDK-demo2-eksdemocdk2ClusterRoleFC35564C-CNS930B6OMG3
```

![image](https://user-images.githubusercontent.com/278432/61603802-a6216880-ac71-11e9-9eaf-c4f6fc7d554e.png)

However, in EKS console `1.13` should be the current latest version.

![image](https://user-images.githubusercontent.com/278432/61603826-ba656580-ac71-11e9-9b04-9e62db72340c.png)

And according to the [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html), the latest version available should be used.

![image](https://user-images.githubusercontent.com/278432/61604183-1086d880-ac73-11e9-82fe-588b3550cee7.png)
